import { useState } from 'react';
import { Building2, Plus, ArrowUpRight, LockKeyhole, CarFront, MapPin, CircleCheck, ShieldCheck } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../components/ui/dialog';
import { Button } from '../components/ui/button';
import { toast } from 'sonner';
import { SERVICE, ServiceIcon, money, STATUS } from './common';
const VehicleArt = ({ service }) => <svg viewBox="0 0 320 120" className={`vehicle-art ${service}`} role="img" aria-label={service === 'fire' ? 'Veículo de combate a incêndios' : service === 'medical' ? 'Ambulância de socorro' : 'Viatura da polícia'}><ellipse cx="160" cy="98" rx="118" ry="7" fill="#000" opacity=".2" /><path d={service === 'police' ? 'M40 77L57 61H97L119 38H207L235 62L274 68V91H40Z' : 'M44 36H216L257 56L270 75V91H44Z'} fill={service === 'fire' ? '#be5049' : service === 'medical' ? '#d3d6bf' : '#d4dedb'} stroke="#101b1a" strokeWidth="3" /><path d={service === 'police' ? 'M108 59L124 43H156V59ZM162 43H203L221 59H162Z' : 'M211 43L249 62H211Z'} fill="#253936" /><path d={service === 'police' ? 'M43 70H268V81H43Z' : 'M45 68H264V79H45Z'} fill={service === 'fire' ? '#e1c572' : service === 'medical' ? '#d7ba4c' : '#436eac'} /><rect x="143" y={service === 'police' ? '32' : '29'} width="32" height="7" rx="2" fill="#629dcc" /><rect x="162" y={service === 'police' ? '32' : '29'} width="14" height="7" rx="1" fill="#db6c60" /><circle cx="91" cy="90" r="16" fill="#111b1b" /><circle cx="91" cy="90" r="8" fill="#71817b" /><circle cx="229" cy="90" r="16" fill="#111b1b" /><circle cx="229" cy="90" r="8" fill="#71817b" /><text x="154" y="65" textAnchor="middle" fontSize="10" fill={service === 'fire' ? '#fbe9d6' : '#1f3931'} fontFamily="Barlow" fontWeight="700">{service === 'fire' ? 'BOMBEIROS' : service === 'medical' ? 'INEM' : 'POLÍCIA'}</text>{service === 'fire' && <g stroke="#813d36" strokeWidth="2"><path d="M53 44H130M53 50H130M53 56H130" /><path d="M179 40V65" /></g>}</svg>;
export default function Management({ game, world, act, busy, mode }) {
  const [buildOpen, setBuildOpen] = useState(false), [service, setService] = useState('fire'), [site, setSite] = useState('north'), [purchase, setPurchase] = useState(null), [baseId, setBaseId] = useState(''), [filter, setFilter] = useState('all');
  const fleet = mode === 'fleet';
  const buy = async () => { const g = await act('buy_vehicle', { base_id: baseId, advanced: purchase.advanced }); if (g) { toast.success('Unidade adquirida e pronta para responder.'); setPurchase(null); } };
  const build = async () => { const g = await act('build_base', { service, site_id: site }); if (g) { toast.success('Nova base operacional. Já podes adquirir veículos.'); setBuildOpen(false); } };
  const openPurchase = (s, advanced = false) => { setPurchase({ service: s, advanced }); setBaseId(game.bases.find(b => b.service === s)?.id || ''); };
  return <main className="management-page"><div className="page-heading"><div><span className="page-eyebrow">RECURSOS OPERACIONAIS</span><h1 data-testid="management-title">{fleet ? 'Frota de emergência' : 'Rede de bases'}</h1><p>{fleet ? `${game.units.length} unidades · ${game.units.filter(u => u.status === 'available').length} disponíveis` : `${game.bases.length} bases operacionais em Porto d'Ouro`}</p></div>{!fleet && <Button data-testid="build-base-open" className="primary-button" onClick={() => setBuildOpen(true)}><Plus size={16} /> Construir base</Button>}</div>
    {!fleet ? <><div className="section-line"><h2>Infraestrutura ativa</h2><span>REDE INTEGRADA 112</span></div><div className="base-grid">{game.bases.map((b, index) => <article className="base-card" key={b.id} data-testid={`base-card-${index}`} style={{ '--service-color': SERVICE[b.service].color }}><div className="base-illustration"><div className="base-skyline"><span /><span /><span /><span /><span /></div><Building2 size={62} strokeWidth={1} /><div className="base-service-label"><ServiceIcon service={b.service} size={13} />{SERVICE[b.service].short}</div></div><div className="base-info"><span className="operational-tag"><i /> OPERACIONAL</span><h3>{b.name}</h3><p><MapPin size={13} />Porto d'Ouro · Setor {index + 1}</p><div className="base-capacity"><span>Capacidade da garagem</span><strong>{game.units.filter(u => u.base_id === b.id).length}/6</strong></div><div className="capacity-track">{Array.from({ length: 6 }, (_, n) => <i key={n} className={n < game.units.filter(u => u.base_id === b.id).length ? 'filled' : ''} />)}</div><button data-testid={`base-buy-vehicle-${index}`} disabled={game.units.filter(u => u.base_id === b.id).length >= 6} onClick={() => { setPurchase({ service: b.service, advanced: false }); setBaseId(b.id); }}>Adquirir veículo <ArrowUpRight size={16} /></button></div></article>)}</div><div className="expansion-strip"><Building2 size={28} /><div><h3>Uma cidade mais protegida.</h3><p>{world.sites.filter(s => !game.bases.some(b => b.node === s.node)).length} terrenos disponíveis para expandir a tua rede.</p></div><Button className="outline-button" data-testid="expand-network-button" onClick={() => setBuildOpen(true)}>Expandir rede <Plus size={16} /></Button></div></> : <>
    <div className="section-line"><h2>Adquirir unidades</h2><span>GARAGEM CENTRAL</span></div><div className="vehicle-grid">{Object.entries(SERVICE).map(([s, info]) => <article key={s} className="vehicle-card" data-testid={`vehicle-shop-${s}`} style={{ '--service-color': info.color }}><div className="vehicle-category"><ServiceIcon service={s} size={17} />{info.short}<span>STANDARD</span></div><VehicleArt service={s} /><h3>{world.services[s].vehicle}</h3><p>Tripulação incluída · Pronto a operar</p><div className="vehicle-price"><strong>{money(world.services[s].price)}</strong><Button className="outline-button" data-testid={`buy-vehicle-${s}`} onClick={() => openPurchase(s)} disabled={game.money < world.services[s].price}><Plus size={15} /> Adquirir</Button></div></article>)}</div>
    <div className="specialist-strip"><div className="specialist-icon"><ShieldCheck size={25} /></div><div><h3>Unidades especializadas</h3><p>Resposta mais rápida e intervenção reforçada.</p></div>{game.level < 2 ? <span data-testid="specialist-locked"><LockKeyhole size={15} /> NÍVEL 2</span> : <div className="specialist-buttons">{Object.entries(SERVICE).map(([s, info]) => <Button key={s} data-testid={`buy-special-${s}`} className="outline-button" onClick={() => openPurchase(s, true)}>{s === 'medical' ? 'VMER' : info.short + ' +'} · {money(world.services[s].price * 2)}</Button>)}</div>}</div>
    <div className="section-line"><h2>As tuas unidades <span>{game.units.length}</span></h2><select aria-label="Filtrar frota" data-testid="fleet-filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Todos os serviços</option>{Object.entries(SERVICE).map(([s, info]) => <option key={s} value={s}>{info.name}</option>)}</select></div><div className="fleet-table"><div className="fleet-row fleet-table-header"><span>UNIDADE</span><span>BASE OPERACIONAL</span><span>ESTADO</span><span>TIPO</span></div>{game.units.filter(u => filter === 'all' || filter === u.service).map(u => <div className="fleet-row" key={u.id} data-testid={`fleet-unit-${u.name}`}><span><ServiceIcon service={u.service} color={SERVICE[u.service].color} /><strong>{u.name}</strong></span><span>{game.bases.find(b => b.id === u.base_id)?.name}</span><span className={`fleet-status ${u.status}`}><i />{STATUS[u.status]}</span><span>{u.advanced ? 'Especializada' : 'Standard'}</span></div>)}</div></>}
    <Dialog open={buildOpen} onOpenChange={setBuildOpen}><DialogContent className="game-modal" data-testid="build-base-modal"><div className="modal-eyebrow"><Building2 size={15} /> EXPANSÃO DA REDE</div><DialogTitle>Construir uma base</DialogTitle><DialogDescription>Escolhe o serviço e a localização. Os veículos são adquiridos separadamente.</DialogDescription><label className="field-label">Serviço<select data-testid="base-service-select" value={service} onChange={e => setService(e.target.value)}>{Object.entries(SERVICE).map(([s, info]) => <option key={s} value={s}>{info.name}</option>)}</select></label><label className="field-label">Localização<select data-testid="base-site-select" value={site} onChange={e => setSite(e.target.value)}>{world.sites.map(s => <option key={s.id} value={s.id} disabled={game.bases.some(b => b.node === s.node)}>{s.name}{game.bases.some(b => b.node === s.node) ? ' · Ocupado' : ''}</option>)}</select></label><div className="purchase-total"><span>Investimento</span><strong data-testid="base-price">{money(world.services[service].base_price)}</strong></div><Button data-testid="buy-station-button" className="primary-button" disabled={busy || game.money < world.services[service].base_price || game.bases.some(b => b.node === world.sites.find(s => s.id === site)?.node)} onClick={build}><Building2 size={16} />{game.money < world.services[service].base_price ? 'Orçamento insuficiente' : 'Confirmar construção'}</Button></DialogContent></Dialog>
    <Dialog open={!!purchase} onOpenChange={v => !v && setPurchase(null)}><DialogContent className="game-modal" data-testid="buy-vehicle-modal"><div className="modal-eyebrow"><CarFront size={15} /> NOVA UNIDADE</div><DialogTitle>Reforçar a frota</DialogTitle><DialogDescription>{purchase && world.services[purchase.service].vehicle}{purchase?.advanced ? ' · Especializada' : ''}</DialogDescription>{purchase && <><VehicleArt service={purchase.service} /><label className="field-label">Base de afetação<select data-testid="vehicle-base-select" value={baseId} onChange={e => setBaseId(e.target.value)}>{game.bases.filter(b => b.service === purchase.service).map(b => <option key={b.id} value={b.id}>{b.name} ({game.units.filter(u => u.base_id === b.id).length}/6)</option>)}</select></label><div className="purchase-total"><span>Veículo e tripulação</span><strong data-testid="vehicle-purchase-price">{money(world.services[purchase.service].price * (purchase.advanced ? 2 : 1))}</strong></div><Button data-testid="buy-vehicle-button" className="primary-button" disabled={busy || !baseId || game.units.filter(u => u.base_id === baseId).length >= 6 || game.money < world.services[purchase.service].price * (purchase.advanced ? 2 : 1)} onClick={buy}><Plus size={16} />Confirmar aquisição</Button></>}</DialogContent></Dialog>
  </main>;
}