import { useState } from 'react';
import { Save, Volume2, RotateCcw, Download, CircleHelp, ShieldCheck } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Switch } from '../components/ui/switch';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../components/ui/dialog';
export default function Settings({ game, act, sound, setSound, onSave, onHelp, busy }) {
  const [reset, setReset] = useState(false);
  const download = () => { const blob = new Blob([JSON.stringify({ city: "Porto d'Ouro", completed: game.completed, xp: game.xp, budget: game.money, trust: game.trust, history: game.history }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'nexo112-relatorio.json'; link.click(); URL.revokeObjectURL(url); };
  return <main className="management-page settings-page"><div className="page-heading"><div><span className="page-eyebrow">PREFERÊNCIAS DA CENTRAL</span><h1 data-testid="settings-title">Definições</h1><p>O teu posto de operação, à tua medida.</p></div></div><section className="settings-section"><h2>Experiência de jogo</h2><div className="setting-row"><Volume2 /><div><h3>Efeitos sonoros</h3><p>Sinais de rádio e alertas de novas ocorrências.</p></div><Switch checked={sound} onCheckedChange={setSound} aria-label="Efeitos sonoros" data-testid="settings-sound-toggle" /></div><div className="setting-row"><CircleHelp /><div><h3>Manual de operações</h3><p>Procedimentos de despacho e gestão de recursos.</p></div><Button className="outline-button" data-testid="settings-help" onClick={onHelp}>Consultar</Button></div></section><section className="settings-section"><h2>Progresso e dados</h2><div className="setting-row"><Save /><div><h3>Guardar progresso</h3><p data-testid="last-save-time">Último registo: {new Date(game.saved_at).toLocaleTimeString('pt-PT')} · Guardado automaticamente neste navegador.</p></div><Button className="outline-button" data-testid="settings-save" onClick={onSave}>Guardar agora</Button></div><div className="setting-row"><Download /><div><h3>Exportar relatório</h3><p>Resumo do turno e histórico de ocorrências em JSON.</p></div><Button className="outline-button" data-testid="export-report" onClick={download}>Exportar</Button></div><div className="setting-row danger-setting"><RotateCcw /><div><h3>Recomeçar a carreira</h3><p>Elimina o progresso atual e inicia um novo turno.</p></div><Button className="danger-button" data-testid="reset-game-open" onClick={() => setReset(true)}>Recomeçar</Button></div></section><div className="settings-note"><ShieldCheck size={19} /><p>Jogo individual de simulação. Cidade, chamadas e ocorrências fictícias.<br />Em caso de emergência real em Portugal, liga 112.</p></div><Dialog open={reset} onOpenChange={setReset}><DialogContent className="game-modal" data-testid="reset-modal"><DialogTitle>Recomeçar a carreira?</DialogTitle><DialogDescription>O orçamento, as bases, a frota e a experiência atuais serão eliminados. Esta ação não pode ser anulada.</DialogDescription><div className="confirm-actions"><Button className="outline-button" data-testid="reset-cancel" onClick={() => setReset(false)}>Manter progresso</Button><Button className="danger-button" data-testid="reset-confirm" disabled={busy} onClick={async () => { if (await act('reset')) setReset(false); }}>Sim, recomeçar</Button></div></DialogContent></Dialog></main>;
}