import { NavLink } from 'react-router-dom';
import { Radio, Map, Building2, CarFront, ChartNoAxesCombined, Settings2, Headphones, Pause, Play, Volume2, VolumeX, Save, Wifi, ChevronDown, CircleHelp, BadgeCheck, Wallet, ShieldCheck } from 'lucide-react';
import { clock, money } from './common';
export const IconButton = ({ icon: Icon, label, onClick, active, testId, ...props }) => <button className={`icon-btn ${active ? 'active' : ''}`} title={label} aria-label={label} data-testid={testId} onClick={onClick} {...props}><Icon size={18} /></button>;
export const Sidebar = ({ onHelp }) => <aside className="nav-rail">
  <NavLink to="/" className="rail-brand" title="NEXO 112" data-testid="brand-home"><Radio size={25} /></NavLink>
  <div className="rail-links">{[[Map, '/', 'Central de operações'], [Building2, '/bases', 'Bases'], [CarFront, '/frota', 'Frota'], [ChartNoAxesCombined, '/relatorios', 'Relatórios']].map(([Icon, path, name]) => <NavLink key={path} end to={path} title={name} aria-label={name} data-testid={`nav-${path === '/' ? 'central' : path.slice(1)}`} className={({ isActive }) => `rail-link ${isActive ? 'active' : ''}`}><Icon size={21} /><span>{name}</span></NavLink>)}</div>
  <div className="rail-bottom"><IconButton icon={CircleHelp} label="Manual de operações" onClick={onHelp} testId="help-button" /><NavLink to="/definicoes" title="Definições" aria-label="Definições" data-testid="nav-definicoes" className="rail-link"><Settings2 size={20} /></NavLink><div className="avatar" data-testid="operator-avatar">OP</div></div>
</aside>;
export const Header = ({ game, act, sound, setSound, onSave }) => <header className="command-header">
  <div className="wordmark" data-testid="game-brand">NEXO<span>112</span><div>CENTRAL DE OPERAÇÕES</div></div>
  <div className="city-switch" data-testid="city-name"><span className="live-dot" /> Porto d'Ouro <ChevronDown size={13} /><small>DISTRITO OPERACIONAL 01</small></div>
  <div className="header-stats"><div className="header-stat budget"><Wallet size={17} /><div><small>ORÇAMENTO</small><strong data-testid="user-budget-display">{money(game.money)}</strong></div></div><div className="header-stat level"><BadgeCheck size={19} /><div><small>OPERADOR · NÍVEL {game.level}</small><strong data-testid="user-level-badge">{game.level === 1 ? 'Recruta' : game.level < 4 ? 'Coordenador' : 'Comandante'}<span>{game.xp % 200}/200 XP</span></strong><div className="xp-track"><i style={{ width: `${game.xp % 200 / 2}%` }} /></div></div></div><div className="header-stat trust"><ShieldCheck size={18} /><div><small>CONFIANÇA</small><strong data-testid="city-trust">{game.trust}<span>%</span></strong></div></div></div>
  <div className="header-actions"><IconButton icon={sound ? Volume2 : VolumeX} label={sound ? 'Desativar som' : 'Ativar som'} onClick={() => setSound(!sound)} testId="sound-toggle" active={sound} /><IconButton icon={Save} label="Guardar progresso" onClick={onSave} testId="save-game-button" /><div className="operator-badge"><Headphones size={19} /><span>Operador 01<small>Em serviço</small></span></div></div>
</header>;
export const Toolbar = ({ game, act }) => <div className="operations-toolbar"><div className="toolbar-heading"><span className="live-dot" /><strong data-testid="operations-title">Central de operações</strong><span className="toolbar-divider" /><span className="live-label">EM DIRETO</span></div><div className="time-controls"><span className="shift-label">TURNO DA TARDE</span><b data-testid="game-clock">{clock(game.elapsed)}</b><div className="speed-group"><IconButton icon={game.speed ? Pause : Play} label={game.speed ? 'Pausar simulação' : 'Retomar simulação'} testId="game-speed-pause" active={!game.speed} onClick={() => act('speed', { speed: game.speed ? 0 : 1 })} />{[1, 2, 5].map(n => <button data-testid={`game-speed-${n}x`} key={n} className={game.speed === n ? 'chosen' : ''} onClick={() => act('speed', { speed: n })}>{n}×</button>)}</div></div></div>;
export const Footer = ({ game, error }) => <footer className="status-footer"><span className={error ? 'connection-error' : ''} data-testid="connection-status"><Wifi size={12} />{error || 'Todos os sistemas operacionais'}</span><span className="footer-middle">PORTO D'OURO <i /> REDE DE EMERGÊNCIA INTEGRADA</span><span data-testid="autosave-status"><span className="live-dot" /> Progresso guardado <span className="version">v1.0</span></span></footer>;