import { NavLink } from 'react-router-dom';
import { Radio, Map, CarFront, ChartNoAxesCombined, Settings2, Headphones, Pause, Play, Volume2, VolumeX, Save, Wifi, ChevronDown, CircleHelp, BadgeCheck, Wallet, ShieldCheck, RadioTower, Flag, Network, Users, Building2, BookOpen } from 'lucide-react';
import { money } from './common';
import { APP_NAME, BRAND_WORD, BRAND_NUMBER } from './branding';
import { reserveFloor } from './engines/economyEngine';
export const IconButton = ({ icon: Icon, label, onClick, active, testId, ...props }) => <button className={`icon-btn ${active ? 'active' : ''}`} title={label} aria-label={label} data-testid={testId} onClick={onClick} {...props}><Icon size={18} /></button>;
export const Sidebar = ({ onHelp, onNavigate }) => <aside className="nav-rail" onClick={event => { if (event.target.closest('a')) onNavigate?.(); }}>
  <nav className="rail-links" aria-label="Navegação principal">{[[Map, '/', 'Central', 'Central de operações'], [Building2, '/gestao', 'Gestão', 'Gestão da rede e recursos'], [ShieldCheck, '/operacoes', 'Operações', 'Operações em curso e apoio'], [Flag, '/estrategia', 'Estratégia', 'Planeamento e prontidão'], [Network, '/alianca', 'Aliança', 'Aliança operacional'], [ChartNoAxesCombined, '/relatorios', 'Relatórios', 'Relatórios e desempenho'], [BookOpen, '/wiki', 'Wiki', 'Enciclopédia operacional do Distrito 112']].map(([Icon, path, name, label]) => <NavLink key={path} end to={path} title={label} aria-label={label} data-testid={`nav-${path === '/' ? 'central' : path.slice(1)}`} className={({ isActive }) => `rail-link ${isActive ? 'active' : ''}`}><Icon size={21} /><span>{name}</span></NavLink>)}</nav>
  <div className="rail-bottom"><IconButton icon={CircleHelp} label="Manual de operações" onClick={onHelp} testId="help-button" /><NavLink to="/definicoes" title="Definições" aria-label="Definições" data-testid="nav-definicoes" className={({ isActive }) => `rail-link ${isActive ? 'active' : ''}`}><Settings2 size={20} /><span>Definições</span></NavLink><NavLink to="/carreira" title="Carreira do operador" aria-label="Carreira do operador" data-testid="nav-carreira" className={({ isActive }) => `avatar ${isActive ? 'active' : ''}`}>OP</NavLink></div>
</aside>;
export const Header = ({ game, act, sound, setSound, onSave }) => <header className="command-header">
  <div className="wordmark brand-wordmark" aria-label={APP_NAME} data-testid="game-brand">{BRAND_WORD}{' '}<span>{BRAND_NUMBER}</span><div>CENTRAL DE OPERAÇÕES</div></div>
  <div className="city-switch" data-testid="city-name"><span className="live-dot" /> {game.city} <ChevronDown size={13} /><small>DISTRITO OPERACIONAL 01</small></div>
  <div className="header-stats"><div className="header-stat budget" title={`Reserva operacional protegida: ${money(reserveFloor(game))} · Financiamento público acumulado: ${money(game.public_funding||0)}`}><Wallet size={17} /><div><small>ORÇAMENTO · RESERVA {money(reserveFloor(game))}</small><strong data-testid="user-budget-display">{money(game.money)}</strong></div></div><div className="header-stat level"><BadgeCheck size={19} /><div><small>OPERADOR · NÍVEL {game.level}</small><strong data-testid="user-level-badge">{game.level === 1 ? 'Operador em formação' : game.level < 4 ? 'Operador' : 'Coordenador de operações'}<span>{game.xp % 200}/200 XP</span></strong><div className="xp-track"><i style={{ width: `${game.xp % 200 / 2}%` }} /></div></div></div><div className="header-stat trust"><ShieldCheck size={18} /><div><small>CONFIANÇA</small><strong data-testid="city-trust" data-tone={game.trust >= 80 ? 'positive' : game.trust >= 50 ? 'warning' : 'negative'}>{game.trust}<span>%</span></strong></div></div></div>
  <div className="header-actions"><IconButton icon={sound ? Volume2 : VolumeX} label={sound ? 'Desativar som' : 'Ativar som'} onClick={() => setSound(!sound)} testId="sound-toggle" active={sound} /><IconButton icon={Save} label="Guardar progresso" onClick={onSave} testId="save-game-button" /><div className="operator-badge"><Headphones size={19} /><span>Operador 01<small>Em serviço</small></span></div></div>
</header>;
export const Toolbar = ({ game, act }) => <div className="operations-toolbar">
  <div className="toolbar-heading"><div className="toolbar-kicker"><span className="live-dot" /> COMANDO & CONTROLO <span> / </span> DISTRITO 01</div><strong data-testid="operations-title">Central de operações<span>.</span></strong></div>
  <div className="toolbar-right"><div className="operational-snapshot" aria-label="Resumo operacional"><div className="snapshot-item"><Radio size={21} /><div><strong data-testid="snapshot-active">{String(game.incidents.length).padStart(2, '0')}</strong><small>ativas</small></div></div><div className="snapshot-item"><CarFront size={22} /><div><strong data-testid="snapshot-ready">{String(game.units.filter(u => u.status === 'available').length).padStart(2, '0')}</strong><small>disponíveis</small></div></div></div>
  <div className="time-controls"><div className="speed-group" aria-label="Velocidade da simulação"><IconButton icon={game.speed ? Pause : Play} label={game.speed ? 'Pausar simulação' : 'Retomar simulação'} testId="game-speed-pause" active={!game.speed} onClick={() => act('speed', { speed: game.speed ? 0 : 1 })} />{[1, 2, 5].map(n => <button aria-label={`Velocidade ${n} vezes`} aria-pressed={game.speed === n} data-testid={`game-speed-${n}x`} key={n} className={game.speed === n ? 'chosen' : ''} onClick={() => act('speed', { speed: n })}>{n}×</button>)}</div></div></div>
</div>;
export const Footer = ({ game, error }) => <footer className="status-footer"><span className={error ? 'connection-error' : ''} data-testid="connection-status"><Wifi size={12} />{error || 'Todos os sistemas operacionais'}</span><span className="footer-middle">PORTUGAL <i /> REDE DE EMERGÊNCIA INTEGRADA · <NavLink to="/privacidade">PRIVACIDADE</NavLink></span><span data-testid="autosave-status"><span className="live-dot" /> Progresso guardado <span className="version">v1.3.0</span></span></footer>;
