import { useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, Flag, Layers3, MapPinned, Route, Settings2, Trophy, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { duration, money, STATUS } from './common';
import './StrategicOperations.css';
import './StrategicControls.css';

export default function StrategicOperations({ game, world, act, busy }) {
  const centers=game.command_centers||[],sites=world.command_center_sites||[];
  const initialCenter=game.active_command_center_id||centers[0]?.id||'';
  const [planned,setPlanned]=useState({title:'Operação planeada',scenario:0,delay:600,site_id:sites[0]?.id||'',command_center_id:initialCenter});
  const [staging,setStaging]=useState({name:'ZC avançada',site_id:sites[0]?.id||'',command_center_id:initialCenter});
  const [complex,setComplex]=useState({name:'Complexo operacional',command_center_id:initialCenter});
  const activeStaging=(game.staging_areas||[]).filter(item=>item.active!==false);
  const availableUnits=useMemo(()=>game.units.filter(unit=>unit.enabled!==false&&['available','patrol','staged'].includes(unit.status)),[game.units]);
  const run=async(kind,data,message)=>{const next=await act(kind,data);if(next&&message)toast.success(message);return next;};

  return <main className="management-page strategy-page">
    <div className="page-heading"><div><span className="page-eyebrow">PLANEAMENTO E PRONTIDÃO</span><h1>Estratégia operacional</h1><p>Prepara meios, organiza complexos e cumpre objetivos antes das grandes operações.</p></div></div>
    <section className="strategy-hero"><div className="strategy-pulse"><i/><Flag size={27}/></div><div><span>SITUAÇÃO ESTRATÉGICA</span><strong>{(game.planned_missions||[]).filter(item=>item.status==='scheduled').length} operações previstas</strong><small>{activeStaging.length} zonas de concentração · {(game.complexes||[]).length} complexos</small></div><div className="strategy-score"><Trophy/><b>{(game.achievements||[]).length}</b><span>marcos</span></div></section>

    <div className="strategy-columns">
      <section className="strategy-panel"><header><CalendarClock/><div><h2>Missões planeadas</h2><p>Agenda eventos e posiciona os recursos antecipadamente.</p></div></header><div className="strategy-form"><input aria-label="Nome da operação" value={planned.title} onChange={event=>setPlanned({...planned,title:event.target.value})}/><select aria-label="Cenário planeado" value={planned.scenario} onChange={event=>setPlanned({...planned,scenario:Number(event.target.value)})}>{world.mission_definitions.slice(0,20).map(item=><option key={item.scenario} value={item.scenario}>{item.name}</option>)}</select><select value={planned.site_id} onChange={event=>setPlanned({...planned,site_id:event.target.value})}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select><select value={planned.command_center_id} onChange={event=>setPlanned({...planned,command_center_id:event.target.value})}>{centers.map(center=><option key={center.id} value={center.id}>{center.name}</option>)}</select><label>Início em <select value={planned.delay} onChange={event=>setPlanned({...planned,delay:Number(event.target.value)})}><option value="300">5 minutos</option><option value="600">10 minutos</option><option value="1800">30 minutos</option><option value="3600">1 hora</option></select></label><Button disabled={busy||!planned.title.trim()} onClick={()=>run('create_planned_mission',planned,'Operação adicionada ao planeamento.')}><CalendarClock size={14}/> Agendar operação</Button></div><div className="strategy-list">{(game.planned_missions||[]).map(item=><article key={item.id} data-state={item.status}><div><strong>{item.title}</strong><small>{item.status==='scheduled'?`T−${duration(Math.max(0,item.starts_at-game.elapsed))}`:item.status==='active'?'Em curso':item.status==='completed'?'Concluída':'Cancelada'}</small></div>{item.status==='scheduled'&&<button aria-label={`Cancelar ${item.title}`} onClick={()=>run('cancel_planned_mission',{planned_id:item.id})}><XCircle size={15}/></button>}</article>)}{!game.planned_missions?.length&&<p className="strategy-empty">Nenhuma operação calendarizada.</p>}</div></section>

      <section className="strategy-panel"><header><MapPinned/><div><h2>Zonas de concentração</h2><p>Desloca viaturas para um ponto avançado através da rede rodoviária.</p></div></header><div className="strategy-form"><input aria-label="Nome da zona" value={staging.name} onChange={event=>setStaging({...staging,name:event.target.value})}/><select value={staging.site_id} onChange={event=>setStaging({...staging,site_id:event.target.value})}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select><select value={staging.command_center_id} onChange={event=>setStaging({...staging,command_center_id:event.target.value})}>{centers.map(center=><option key={center.id} value={center.id}>{center.name}</option>)}</select><Button disabled={busy||!staging.name.trim()} onClick={()=>run('create_staging_area',staging,'Zona de concentração criada.')}><MapPinned size={14}/> Criar zona</Button></div><div className="strategy-list">{activeStaging.map(area=><article className="staging-card" key={area.id}><div><strong>{area.name}</strong><small>{area.city} · {game.units.filter(unit=>unit.staging_area_id===area.id).length} viaturas</small></div><select aria-label={`Mobilizar para ${area.name}`} defaultValue="" onChange={event=>{if(event.target.value)run('deploy_to_staging',{staging_id:area.id,unit_id:event.target.value},'Mobilização iniciada.');event.target.value='';}}><option value="">Mobilizar viatura…</option>{availableUnits.filter(unit=>unit.land===area.land&&unit.staging_area_id!==area.id).map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></article>)}{!activeStaging.length&&<p className="strategy-empty">Sem zonas temporárias ativas.</p>}</div></section>
    </div>

    <div className="strategy-columns lower">
      <section className="strategy-panel"><header><Layers3/><div><h2>Complexos de edifícios</h2><p>Agrupa infraestrutura da mesma área numa unidade de gestão.</p></div></header><div className="strategy-form inline"><input value={complex.name} onChange={event=>setComplex({...complex,name:event.target.value})}/><select value={complex.command_center_id} onChange={event=>setComplex({...complex,command_center_id:event.target.value})}>{centers.map(center=><option key={center.id} value={center.id}>{center.name}</option>)}</select><Button onClick={()=>run('create_complex',complex,'Complexo criado.')} disabled={busy||!complex.name.trim()}><Layers3 size={14}/> Criar</Button></div><div className="complex-grid">{(game.complexes||[]).map(item=><article key={item.id}><h3>{item.name}</h3><small>{(item.base_ids||[]).length} bases · {(item.facility_ids||[]).length} instalações</small><div>{game.bases.filter(base=>base.command_center_id===item.command_center_id).map(base=><label key={base.id}><input type="checkbox" checked={(item.base_ids||[]).includes(base.id)} onChange={()=>run('toggle_complex_member',{complex_id:item.id,member_kind:'base',member_id:base.id})}/>{base.name}</label>)}{game.facilities.filter(facility=>facility.command_center_id===item.command_center_id).map(facility=><label key={facility.id}><input type="checkbox" checked={(item.facility_ids||[]).includes(facility.id)} onChange={()=>run('toggle_complex_member',{complex_id:item.id,member_kind:'facility',member_id:facility.id})}/>{facility.name}</label>)}</div></article>)}</div></section>

      <section className="strategy-panel"><header><Trophy/><div><h2>Tarefas e marcos</h2><p>Objetivos de carreira com recompensas operacionais.</p></div></header><div className="task-list">{(game.tasks||[]).map(task=>{const done=task.progress>=task.target;return <article key={task.id} className={done?'done':''}><div className="task-icon">{done?<CheckCircle2/>:<Route/>}</div><div><strong>{task.title}</strong><span><i style={{width:`${Math.min(100,task.progress/task.target*100)}%`}}/></span><small>{task.progress}/{task.target} · {money(task.reward)}</small></div><Button disabled={!done||task.claimed||busy} onClick={()=>run('claim_task',{task_id:task.id},'Recompensa recebida.')}>{task.claimed?'Recebida':'Recolher'}</Button></article>})}</div><div className="achievement-row">{(game.achievements||[]).map(item=><span key={item.id}><Trophy size={13}/>{item.title}</span>)}</div></section>
    </div>

    <div className="section-line"><h2>Controlos avançados da frota</h2><span>DISPONIBILIDADE · RAR · TRANSFERÊNCIA</span></div>
    <div className="unit-control-grid">{game.units.map(unit=><article key={unit.id}><header><Settings2/><div><strong>{unit.name}</strong><small>{unit.enabled===false?'Inativa':STATUS[unit.status]||unit.status}</small></div>{unit.status==='staged'&&<button onClick={()=>run('return_from_staging',{unit_id:unit.id},'Regresso à base iniciado.')}><Route size={13}/> Regressar</button>}</header><label><input type="checkbox" checked={unit.enabled!==false} onChange={event=>run('update_unit_settings',{unit_id:unit.id,enabled:event.target.checked})}/> Ativa</label><label><input type="checkbox" checked={unit.exclude_from_arr===true} onChange={event=>run('update_unit_settings',{unit_id:unit.id,exclude_from_arr:event.target.checked})}/> Excluir dos RAR</label><label>Lotação máxima <input type="number" min={unit.crew_required||1} max="12" value={unit.max_crew||unit.crew_required||1} onChange={event=>run('update_unit_settings',{unit_id:unit.id,max_crew:event.target.value})}/></label><label>Atraso de saída <input type="number" min="0" max="120" value={unit.response_delay||0} onChange={event=>run('update_unit_settings',{unit_id:unit.id,response_delay:event.target.value})}/> s</label><select aria-label={`Transferir ${unit.name}`} value={unit.base_id} onChange={event=>run('transfer_unit',{unit_id:unit.id,base_id:event.target.value},'Viatura transferida.')}>{game.bases.filter(base=>base.service===unit.service).map(base=><option key={base.id} value={base.id}>{base.name}</option>)}</select></article>)}</div>
  </main>;
}
