import { useMemo, useState } from 'react';
import { CalendarClock, Flag, MapPinned, Route, Trophy, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { duration } from './common';
import './StrategicOperations.css';
import './StrategicControls.css';

export default function StrategicOperations({ game, world, act, busy }) {
  const centers=game.command_centers||[],sites=world.command_center_sites||[],initialCenter=game.active_command_center_id||centers[0]?.id||'';
  const [planned,setPlanned]=useState({title:'Operação planeada',scenario:0,delay:600,site_id:sites[0]?.id||'',command_center_id:initialCenter});
  const [staging,setStaging]=useState({name:'ZC avançada',site_id:sites[0]?.id||'',command_center_id:initialCenter});
  const activeStaging=(game.staging_areas||[]).filter(item=>item.active!==false);
  const availableUnits=useMemo(()=>game.units.filter(unit=>unit.enabled!==false&&game.bases.find(base=>base.id===unit.base_id)?.enabled!==false&&['available','patrol','staged'].includes(unit.status)),[game.units,game.bases]);
  const run=async(kind,data,message)=>{const next=await act(kind,data);if(next&&message)toast.success(message);return next;};

  return <main className="management-page strategy-page">
    <div className="page-heading"><div><span className="page-eyebrow">PLANEAMENTO E PRONTIDÃO</span><h1>Estratégia operacional</h1><p>Planeia missões, posicionamento antecipado e políticas de despacho.</p></div></div>
    <section className="strategy-hero"><div className="strategy-pulse"><i/><Flag size={27}/></div><div><span>SITUAÇÃO ESTRATÉGICA</span><strong>{(game.planned_missions||[]).filter(item=>item.status==='scheduled').length} operações previstas</strong><small>{activeStaging.length} zonas de concentração · {game.units.filter(unit=>unit.on_shift!==false).length} meios em turno</small></div><div className="strategy-score"><Trophy/><b>{availableUnits.length}</b><span>meios prontos</span></div></section>

    <div className="strategy-columns">
      <section className="strategy-panel"><header><CalendarClock/><div><h2>Missões planeadas</h2><p>Agenda eventos e posiciona recursos antecipadamente. Operações criadas pelo jogador custam 100 € e têm recompensa reduzida.</p></div></header><div className="strategy-form"><input aria-label="Nome da operação" value={planned.title} onChange={event=>setPlanned({...planned,title:event.target.value})}/><select aria-label="Cenário planeado" value={planned.scenario} onChange={event=>setPlanned({...planned,scenario:Number(event.target.value)})}>{world.mission_definitions.slice(0,30).map(item=><option key={item.scenario} value={item.scenario}>{item.name}</option>)}</select><select value={planned.site_id} onChange={event=>setPlanned({...planned,site_id:event.target.value})}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select><select value={planned.command_center_id} onChange={event=>setPlanned({...planned,command_center_id:event.target.value})}>{centers.map(center=><option key={center.id} value={center.id}>{center.name}</option>)}</select><label>Início em <select value={planned.delay} onChange={event=>setPlanned({...planned,delay:Number(event.target.value)})}><option value="300">5 minutos</option><option value="600">10 minutos</option><option value="1800">30 minutos</option><option value="3600">1 hora</option></select></label><Button data-action-tone={(game.money||0) >= 100 ? 'positive' : 'supported'} disabled={busy||!planned.title.trim()} onClick={()=>run('create_planned_mission',planned,'Operação planeada e orçamento reservado.')}><CalendarClock size={14}/> Agendar</Button></div><div className="strategy-list">{(game.planned_missions||[]).map(item=><article key={item.id} data-state={item.status}><div><strong>{item.title}</strong><small>{item.status==='scheduled'?'T−'+duration(Math.max(0,item.starts_at-game.elapsed)):item.status==='active'?'Em curso':item.status==='completed'?'Concluída':'Cancelada'}</small></div>{item.status==='scheduled'&&<button aria-label={'Cancelar '+item.title} onClick={()=>run('cancel_planned_mission',{planned_id:item.id})}><XCircle size={15}/></button>}</article>)}</div></section>
      <section className="strategy-panel"><header><MapPinned/><div><h2>Zonas de concentração</h2><p>Desloca meios para pontos avançados antes de uma operação.</p></div></header><div className="strategy-form"><input value={staging.name} onChange={event=>setStaging({...staging,name:event.target.value})}/><select value={staging.site_id} onChange={event=>setStaging({...staging,site_id:event.target.value})}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select><select value={staging.command_center_id} onChange={event=>setStaging({...staging,command_center_id:event.target.value})}>{centers.map(center=><option key={center.id} value={center.id}>{center.name}</option>)}</select><Button disabled={busy||!staging.name.trim()} onClick={()=>run('create_staging_area',staging,'Zona criada.')}><MapPinned size={14}/> Criar</Button></div><div className="strategy-list">{activeStaging.map(area=>{const stagedUnits=game.units.filter(unit=>unit.staging_area_id===area.id);return <article key={area.id}><div><strong>{area.name}</strong><small>{area.city} · {stagedUnits.length} viaturas</small>{stagedUnits.map(unit=><button key={unit.id} className="outline-button" disabled={busy} onClick={()=>run('return_from_staging',{unit_id:unit.id},'Regresso à base iniciado.')}>Regressar · {unit.callsign||unit.name}</button>)}</div><select defaultValue="" onChange={event=>{if(event.target.value)run('deploy_to_staging',{staging_id:area.id,unit_id:event.target.value},'Mobilização iniciada.');event.target.value='';}}><option value="">Mobilizar…</option>{availableUnits.filter(unit=>unit.land===area.land&&unit.staging_area_id!==area.id).map(unit=><option key={unit.id} value={unit.id}>{unit.callsign||unit.name}</option>)}</select><button className="outline-button" disabled={busy||stagedUnits.length>0} onClick={()=>run('close_staging_area',{staging_id:area.id},'Zona de concentração encerrada.')}><XCircle size={14}/> Fechar</button></article>})}</div></section>
    </div>

    <section className="strategy-panel"><header><Route/><div><h2>Política de despacho</h2><p>Define reservas mínimas, distância máxima e automatismos de transporte.</p></div></header><div className="policy-grid"><label>Distância máxima<input type="number" min="5" max="300" value={game.dispatch_policy?.max_response_km||80} onChange={event=>run('update_dispatch_policy',{max_response_km:Number(event.target.value)})}/><span>km</span></label>{['fire','medical','police'].map(service=><label key={service}>Reserva {service==='fire'?'bombeiros':service==='medical'?'médica':'policial'}<input type="number" min="0" max="20" value={game.dispatch_policy?.reserve_by_service?.[service]||0} onChange={event=>run('update_dispatch_policy',{reserve_by_service:{[service]:Number(event.target.value)}})}/></label>)}<label><input type="checkbox" checked={game.dispatch_policy?.prefer_fastest!==false} onChange={event=>run('update_dispatch_policy',{prefer_fastest:event.target.checked})}/> Priorizar chegada mais rápida</label><label><input type="checkbox" checked={game.dispatch_policy?.allow_returning_redirect===true} onChange={event=>run('update_dispatch_policy',{allow_returning_redirect:event.target.checked})}/> Permitir redirecionar meios em regresso</label><label><input type="checkbox" checked={game.dispatch_policy?.auto_patient_transport===true} onChange={event=>run('update_dispatch_policy',{auto_patient_transport:event.target.checked})}/> Transporte médico automático</label><label><input type="checkbox" checked={game.dispatch_policy?.auto_prisoner_transport===true} onChange={event=>run('update_dispatch_policy',{auto_prisoner_transport:event.target.checked})}/> Transporte prisional automático</label></div></section>
  </main>;
}
